### ISSUE TITLE
Vamos a mejorar la comparación

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/dorcar-s2-evaluacion-intermedia-Fanyfa#4]
Ahora pillamos el número que ha escrito el usuario y lo convertimos a número (superbien!!).

A la hora de comparar hemos planteado dos opciones: 

- si es mayor
- si es menor o igual

Deberíamos tener 3: mayor, menor o igual.

![Whaaat?](https://media.giphy.com/media/l3vRioHcAYTTZbXQA/giphy.gif)

**Comment by Fanyfa** [comment]
hecho!

**Comment by oneeyedman** [comment]
Realmente se podría resolver con un un
```
if(number < numberRandom) {
    clue('demasiado bajo');
  } else if(number > numberRandom) {
    clue('demasiado alto');
  } else {
    clue('correcto');
  }
```
Pero queríamos que viéseis que cuando recogemos con `.innerHTML` o `.value`, estamos recogiendo cadenas.

Muy bien hecho!
